## Neural Network (not in use)

In [1]:
# import pandas as pd
# import tensorflow as tf
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import LabelEncoder, StandardScaler

# X = data[['product_category_name_english','purchase_month','location_cluster' ]]  # Selecteer kenmerken

# y = data['price_cluster']  # Selecteer label

# print("Shape of X:", X.shape)
# print("Shape of y:", y.shape)

# scaler = StandardScaler()
# X_scaled = scaler.fit_transform(X)

# # Split de dataset in trainings- en testsets
# X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# # Bouw het neuraal netwerkmodel
# model = tf.keras.models.Sequential([
#     tf.keras.layers.Flatten(input_shape=(3,)),
#     tf.keras.layers.Dense(100, activation='relu'),
#     tf.keras.layers.Dense(100, activation='relu'),
#     tf.keras.layers.Dense(5, activation='softmax'),
# ])

# # Compileer het model
# model.compile(optimizer='adam',
#               loss='mean_squared_error',
#               metrics=['accuracy'])

# # Train het model
# model.fit(X_train, y_train, epochs=10, batch_size=50, validation_split=0.2)

# # Evaluatie van het model
# loss, accuracy = model.evaluate(X_test, y_test)
# print("Test loss:", loss)
# print("Test accuracy:", accuracy)

## Import libs, merge data and starting shite

In [1]:
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd
import warnings
from sklearn.linear_model import LogisticRegression
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=DeprecationWarning, module='tensorflow')
orders =  pd.read_csv("olist_orders_dataset.csv")
data_shane =  pd.read_csv("olist_data.csv")
# # Voer de merge uit op basis van het product ID
data = pd.merge(orders, data_shane, on='order_id')
data.fillna(0, inplace=True)
data.head()

,order_id,customer_id_x,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,Unnamed: 0,product_id,price,product_category_name_english,customer_id_y,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,0,87285b34884572647811a353c7ac498a,29.99,housewares,9ef432eb6251297304e76186b10a928d,-23.583452,-46.586284,são paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,118.70,perfumery,b0830fb4747a6c6d20dea0b8c802d7ef,-12.124719,-45.011148,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,2,aa4383b373c6aca5d8797843e5594415,159.90,auto,41ce2a54c0b03bf3443c3d931a367089,-16.743570,-48.511633,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,3,d0b61bfb1de832b15ba9d266ca96e5b0,45.00,pet_shop,f88197465ea7920adcdbec7375364d82,-5.773119,-35.272557,são gonçalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,4,65266b2da20d04dbe00c5c2d3bb7859e,19.90,stationery,8ab97904e6daea8866dbdbc4fb7aad2c,-23.674612,-46.518300,santo andre,SP

## Clustering of geolocaties and prices

In [16]:
#Cluster of geolocaties
geolocaties = data[['geolocation_lat', 'geolocation_lng']].values
aantal_clusters = 100
kmeans = KMeans(n_clusters=aantal_clusters, random_state=0)
kmeans.fit(geolocaties)
data['location_cluster'] = kmeans.labels_

In [24]:
#Cluster of prices
price_cluster = data[['price']].values
aantal_clusters = 9
kmeans = KMeans(n_clusters=aantal_clusters, random_state=0)
kmeans.fit(price_cluster)
data['price_cluster'] = kmeans.labels_

print('Aantal clusters is', data['price_cluster'].max() + 1)

prijsranges = [(cluster, data[data['price_cluster'] == cluster]['price'].min(), data[data['price_cluster'] == cluster]['price'].max()) for cluster in range(data['price_cluster'].max() + 1)]

print("Lijst van alle clusters en de prijsranges:")
for cluster, min_prijs, max_prijs in prijsranges:
    print(f"Cluster {cluster}: Prijsrange {min_prijs} - {max_prijs}")

Aantal clusters is 9
Lijst van alle clusters en de prijsranges:
Cluster 0: Prijsrange 135.28 - 245.7
Cluster 1: Prijsrange 723.74 - 1125.9
Cluster 2: Prijsrange 0.0 - 66.3
Cluster 3: Prijsrange 1788.0 - 3124.0
Cluster 4: Prijsrange 245.9 - 441.0
Cluster 5: Prijsrange 3399.99 - 6735.0
Cluster 6: Prijsrange 442.95 - 722.5
Cluster 7: Prijsrange 66.38 - 135.21
Cluster 8: Prijsrange 1129.0 - 1780.0

In [25]:
# Bereken het aantal producten per cluster
producten_per_cluster = data['price_cluster'].value_counts()

print("Aantal producten per cluster:")
print(producten_per_cluster)

# Identificeer het duurste cluster
duurste_cluster = prijsranges[-1][0]  # Het laatste cluster in de lijst, omdat de lijst is gesorteerd op prijs

duurste_cluster_data = data[data['price_cluster'] == duurste_cluster]

productcategorieen_in_duurste_cluster = duurste_cluster_data['product_category_name_english'].value_counts()

print("\nProductcategorieën in het duurste cluster:")
print(productcategorieen_in_duurste_cluster)

Aantal producten per cluster:
price_cluster
2    51611
7    33988
0    17609
4     6377
6     2136
1     1008
8      472
3      205
5       19
Name: count, dtype: int64

Productcategorieën in het duurste cluster:
product_category_name_english
computers                                  90
health_beauty                              59
watches_gifts                              58
sports_leisure                             30
auto                                       28
computers_accessories                      28
garden_tools                               26
small_appliances                           17
fixed_telephony                            16
housewares                                 14
home_appliances_2                          12
musical_instruments                        11
furniture_decor                             8
construction_tools_construction             8
toys                                        8
baby                                        6
agro_industry_and_commerce                  6
telephony                                   5
consoles_games                              5
0                                           4
bed_bath_table                              4
pet_shop                                    3
luggage_accessories                         3
electronics                                 3
office_furniture                            2
construction_tools_safety                   2
dvds_blu_ray                                2
industry_commerce_and_business              2
small_appliances_home_oven_and_coffee       2
fashion_bags_accessories                    2
stationery                                  1
home_appliances                             1
cool_stuff                                  1
music                                       1
construction_tools_lights                   1
kitchen_dining_laundry_garden_furniture     1
costruction_tools_garden                    1
air_conditioning                            1
Name: count, dtype: int64

In [26]:
# Bereken het aantal producten per productcategorie in het duurste cluster met de gecodeerde productcategorieën
productcategorieen_in_duurste_cluster_encoded = duurste_cluster_data['product_category_name_english_encoded'].value_counts()

print("\nGecodeerde productcategorieën in het duurste cluster:")
print(productcategorieen_in_duurste_cluster_encoded)

Gecodeerde productcategorieën in het duurste cluster:
product_category_name_english_encoded
15    90
44    59
71    58
66    30
6     28
16    28
43    26
64    17
35    16
50    14
46    12
57    11
40     8
18     8
70     8
7      6
1      6
69     5
17     5
0      4
8      4
61     3
54     3
27     3
58     2
20     2
26     2
51     2
65     2
29     2
67     1
45     1
21     1
56     1
19     1
52     1
22     1
2      1
Name: count, dtype: int64

In [27]:
# Zorg ervoor dat alle waarden in de kolom 'product_category_name_english' strings zijn
from sklearn.preprocessing import LabelEncoder
data['product_category_name_english'] = data['product_category_name_english'].astype(str)
data['product_category_name_english_encoded'] = LabelEncoder().fit_transform(data['product_category_name_english'])

# Tijd van het jaar
data['order_purchase_timestamp'] = pd.to_datetime(data['order_purchase_timestamp'])
data['purchase_month'] = data['order_purchase_timestamp'].dt.month
data['purchase_month'] = data['purchase_month'].apply(lambda x: x if x <= 12 else x - 12)

# data = data.drop(['customer_id_x', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'Unnamed: 0','customer_id_y', 'geolocation_lat',	'geolocation_lng'], axis=1)

# Print de bijgewerkte dataset
data

,order_id,customer_id_x,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,Unnamed: 0,product_id,...,product_category_name_english,customer_id_y,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state,location_cluster,price_cluster,product_category_name_english_encoded,purchase_month
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,0,87285b34884572647811a353c7ac498a,...,housewares,9ef432eb6251297304e76186b10a928d,-23.583452,-46.586284,são paulo,SP,78,2,50,10
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,...,perfumery,b0830fb4747a6c6d20dea0b8c802d7ef,-12.124719,-45.011148,barreiras,BA,56,7,60,7
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,2,aa4383b373c6aca5d8797843e5594415,...,auto,41ce2a54c0b03bf3443c3d931a367089,-16.743570,-48.511633,vianopolis,GO,48,0,6,8
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,3,d0b61bfb1de832b15ba9d266ca96e5b0,...,pet_shop,f88197465ea7920adcdbec7375364d82,-5.773119,-35.272557,são gonçalo do amarante,RN,53,2,61,11
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,4,65266b2da20d04dbe00c5c2d3bb7859e,...,stationery,8ab97904e6daea8866dbdbc4fb7aad2c,-23.674612,-46.518300,santo andre,SP,78,2,67,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113420,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,113420,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,baby,1fca14ff2861355f6e5f14306ff977a7,-24.000240,-46.447516,praia grande,SP,9,0,7,2
113421,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,113421,b80910977a37536adeddd63663f916ad,...,home_appliances_2,1aa71eb042121263aafbe80c1b562c9c,-17.891478,-39.373044,nova vicosa,BA,52,0,46,8
113422,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,113422,d1c427060a0f73f6b889a5c7c61f2ac4,...,computers_accessories,b331b74b18dc79bcdf6532d51e1637c1,-22.549165,-42.685143,japuiba,RJ,4,0,16,1
113423,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,113423,d1c427060a0f73f6b889a5c7c61f2ac4,...,computers_accessories,b331b74b18dc79bcdf6532d51e1637c1,-22.549165,-42.685143,japuiba,RJ,4,0,16,1
113424,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,113424,006619bbed68b000c8ba3f8725d5409e,...,health_beauty,edb027a75a1449115f6b43211ae02a24,-25.766216,-49.724982,lapa,PR,43,7,44,3

In [30]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
X = data[['product_category_name_english_encoded','purchase_month','location_cluster' ]]  # Selecteer kenmerken

y = data['price_cluster']  # Selecteer label

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = np.mean(y_pred == y_test)
print("Accuracy:", accuracy)

Accuracy: 0.4518404231871281

C:\Users\Gebruiker\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

(90740, 3)

In [22]:
import numpy as np

# Vraag de gebruiker om de maand, prijscategorie en locatiecluster in te voeren
purchase_month = int(input("In welke maand is het (geef aan met een getal): "))
product_category_name_english = int(input("Wat is de productcategorie naam?: "))
location_cluster = int(input("In welk cluster woon je (geef aan met een getal): "))

# Zet de ingevoerde waarden om in een numpy array met de juiste vorm (1 bij 3 array)
X_array = np.array([[purchase_month, product_category_name_english, location_cluster]])

# Voorspel de prijscluster
predicted_price_cluster = model.predict(X_array)

print("Voorspelde prijscluster:", predicted_price_cluster)

In welke maand is het (geef aan met een getal):  7
Wat is de productcategorie naam?:  71
In welk cluster woon je (geef aan met een getal):  8

Voorspelde prijscluster: [3]

C:\Users\Gebruiker\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(